### ISSUE TITLE
Type hinting in Shapely 2.0

### ISSUE THREAD

**Issue by tomplex** [shapely/shapely-rfc#4]
I haven't participated in one of these before, so please let me know if there's a particular procedure I should follow with regards to adding an item for discussion.

I'd really love to see the Python parts of Shapely 2.0 leverage type hinting, especially for public functions / methods. I think it helps significantly with both client usage and maintenance, and while it could be a little arduous to add type hints to everything that it would be a net positive to the codebase.

**Comment by mwtoews** [comment]
This was suggested in https://github.com/Toblerity/Shapely/issues/721

I think this feature can be discussed/merged into `master` for Shapely 1.8, as they shouldn't pose any backwards incompatible changes, now that the code base uses Python 3.5+. (Normally I see an RFC process to prepare and discuss large changes with potential incompatibilities.)

**Comment by tomplex** [comment]
Awesome, thanks for the response @mwtoews!
